version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=super_secret_buildathon2026
      - GROQ_API_KEY=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
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api

    depends_on:
      - backend
